-- ============================================================
-- Recurrence editing: allow changing the schedule of recurring tasks
-- Google-Calendar style (this one / this and following / all).
--
-- A recurring task is a `task_templates` row + `task_occurrences` rows.
--
-- RPC `update_task_template` ПОЛНОСТЬЮ определён в более поздней миграции
-- 20260807_google_calendar_actions.sql (та же логика + p_new_start_date,
-- p_category_id). Здесь он НЕ создаётся: в Postgres `CREATE OR REPLACE`
-- не заменяет функцию при изменении сигнатуры аргументов, а создаёт
-- перегрузку (ошибка 42725), поэтому отдельная 16-параметровая версия
-- из этой миграции конфликтовала бы с полной 18-параметровой.
-- На свежей БД миграции применяются по алфавиту имён: google_calendar_actions
-- идёт раньше recurrence_editing и создаёт функцию первой.
--
-- Если в БД уже осталась перегрузка (две версии update_task_template),
-- снять старую вручную:
--   DROP FUNCTION IF EXISTS public.update_task_template(
--     uuid, text, text, text, integer, time, timestamptz, recurrence_type,
--     integer, smallint[], date, date, integer, uuid, uuid, uuid[]);
-- ============================================================
